Problem Statement : Hospital Patient Data Analysis

Context:

A hospital maintains patient records including admission details, department, diagnosis, doctor, and bill amount. You have two datasets: one with patient info and another with billing details. Some patients have blank bill amounts, and there are multiple rows for the same patient due to follow-ups.

Tasks:

1.	Load the patient dataset and show summary with info().

2.	Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount'].

3.	Drop administrative columns like ['ReceptionistID', 'CheckInTime'].

4.	Use groupby to find total bill amount per department.

5.	Remove duplicate patient records based on PatientID.

6.	Fill missing BillAmount values with the mean bill amount.

7.	Merge the billing dataset with patient dataset on PatientID.

8.	Concatenate an additional DataFrame that contains new patients for the current week (row-wise).

9.	Concatenate new billing category columns like ['InsuranceCovered', 'FinalAmount'] (column-wise).

In [1]:
import pandas as pd

In [8]:
data = pd.read_csv(r"C:\Users\gowra\Downloads\Patient_Data.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [7]:
df = pd.DataFrame(data)
df

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00

In [17]:
df[["PatientID","Department","Doctor","BillAmount"]]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [18]:
df.drop(columns=["ReceptionistID","CheckInTime"], inplace=True)

In [19]:
df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [38]:
total_BA = df.groupby("Department")["BillAmount"].sum()
display(total_BA)

Department
Cardiology     11200.000000
Dermatology     6233.333333
Neurology       6233.333333
Orthopedics     7500.000000
Name: BillAmount, dtype: float64

In [47]:
df.drop_duplicates(inplace=True)

In [48]:
df.duplicated(subset=['PatientID'])

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [26]:
df.fillna(df["BillAmount"].mean(), inplace=True)
df

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [28]:
df1 = pd.read_csv(r"C:\Users\gowra\Downloads\Billing_Data.csv")
df1

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [29]:
df2 = pd.merge(df, df1, on="PatientID")

In [30]:
df2

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [35]:
df3 = pd.concat([df1,df2])
df3

,PatientID,InsuranceCovered,FinalAmount,Name,Department,Doctor,BillAmount
0,101,2000,3000,NaN,NaN,NaN,NaN
1,102,1500,3500,NaN,NaN,NaN,NaN
2,103,2500,5000,NaN,NaN,NaN,NaN
3,104,3000,3200,NaN,NaN,NaN,NaN
4,105,1000,4000,NaN,NaN,NaN,NaN
0,101,2000,3000,Alice,Cardiology,Dr. Smith,5000.000000
1,102,1500,3500,Bob,Neurology,Dr. John,6233.333333
2,103,2500,5000,Charlie,Orthopedics,Dr. Lee,7500.000000
3,104,3000,3200,David,Cardiology,Dr. Smith,6200.000000
4,105,1000,4000,Eva,Dermatology,Dr. Rose,6233.333333

In [37]:
new_patients_data = {
    'PatientID': [106, 107],
    'Name': ['David', 'Sarah'],
    'Department': ['Pediatrics', 'Oncology'],
    'Doctor': ['Dr. White', 'Dr. Black'],
    'BillAmount': [4500.0, 9000.0],
    'ReceptionistID': [3, 4],
    'CheckInTime': ['2023-01-15 13:33', '2023-01-15 11:11']
}
new_patients_df = pd.DataFrame(new_patients_data)

In [42]:
updated_df = pd.concat([data,new_patients_df])
display(updated_df)

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45
5,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
0,106,David,Pediatrics,Dr. White,4500.0,3,2023-01-15 13:33
1,107,Sarah,Oncology,Dr. Black,9000.0,4,2023-01-15 11:11

In [43]:
billing_columns = df1[['InsuranceCovered', 'FinalAmount']]
patient_with_billing = pd.concat([df, billing_columns], axis=1)
display(patient_with_billing)

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000