1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
lst = [2,4,5,6,8]
lst.append(10)
lst

[2, 4, 5, 6, 8, 10]

In [3]:
lst = [2,4,5,6,8]
lst.extend([10,12,14])
lst

[2, 4, 5, 6, 8, 10, 12, 14]

In [4]:
lst.insert(2,15)
lst

[2, 4, 15, 5, 6, 8, 10, 12, 14]

In [5]:
lst.remove(10)
lst

[2, 4, 15, 5, 6, 8, 12, 14]

In [ ]:
lst.pop(6)
lst

[2, 4, 15, 5, 6, 8, 14]

In [10]:
lst.index(4)

1

In [11]:
lst.count(4)

1

In [21]:
lst.sort()
lst

[2, 4, 5, 6, 8, 14, 15]

In [22]:
lst.reverse()
lst

[15, 14, 8, 6, 5, 4, 2]

In [23]:
lst.clear()
lst

[]

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [24]:
stu = ('gowra','sai','kiran')
stu

('gowra', 'sai', 'kiran')

In [25]:
stu[2] = 'reddy'  # This will raise an error because tuples are immutable

TypeError: 'tuple' object does not support item assignment

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [26]:
set1 = {1,2,2,2,3,3,3,3,4,5,5,6,6,6,7}
print(set1)
# set remove the duplicate values and store only unique values

{1, 2, 3, 4, 5, 6, 7}

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [28]:
dic = {
    'name':'gowrav',
    'age':24,
    'city':'hyd'
       
       }
dic 
dic['age'] = 21
dic['email'] = 'gowravenugulaa@gmail.com'
dic

{'name': 'gowrav',
 'age': 21,
 'city': 'hyd',
 'email': 'gowravenugulaa@gmail.com'}

5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [29]:
age = int(input("enter your age:"))
if age>=18:
    print("you are eligible to vote")
else:
    print("you are not eligible to vote")

you are not eligible to vote

6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [39]:
mark = int(input("enter your mark:"))
if mark>=90:
    print("A grade")
elif mark>=75:
    print("B grade")
elif mark>=50:
    print("C grade")
else:
    print("fail")

B grade

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative

In [46]:
num = int(input("enter a number:"))
if num>0:
    if num%2==0:
        print("positive even number")
    print("positive number")
elif num==0:
    print("number is zero")
else:
    print("negative number")

positive number

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [54]:
import numpy as np 
scalar = np.array(5)
print("Scalar:", scalar)

Scalar: 5

In [55]:
arr1 = np.array([1,2,3,4,5])
print("1D Array:", arr1)

1D Array: [1 2 3 4 5]

In [56]:
arr2 = np.array([[10,20,30],[40,50,60]])
print("2D Array:\n", arr2)

2D Array:
 [[10 20 30]
 [40 50 60]]

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [57]:
random_arr = np.random.randint(1,100,size=(4,4))
random_arr

array([[75, 22, 75, 36],
       [26, 31,  2, 68],
       [15, 80, 99, 21],
       [21, 60, 61, 60]])

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [58]:
import pandas as pd
data = ([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(data, columns=['A','B','C'])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [88]:
data1 = {
    'Name': ['gowrav','gowrav', 'sai', 'kiran'],
    'Age': [24, 24, 23, 22],
    'City': ['hyd', 'hyd', 'bang', 'chennai'],
    'Salary': [50000, 50000, np.nan, 55000]
}
df1 = pd.DataFrame(data1)
df1

     Name  Age     City   Salary
0  gowrav   24      hyd  50000.0
1  gowrav   24      hyd  50000.0
2     sai   23     bang      NaN
3   kiran   22  chennai  55000.0

In [89]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   City    4 non-null      object
 3   Salary  3 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

In [90]:
df1.describe()

             Age        Salary
count   4.000000      3.000000
mean   23.250000  51666.666667
std     0.957427   2886.751346
min    22.000000  50000.000000
25%    22.750000  50000.000000
50%    23.500000  50000.000000
75%    24.000000  52500.000000
max    24.000000  55000.000000

In [91]:
df1[['Name','City']]

     Name     City
0  gowrav      hyd
1  gowrav      hyd
2     sai     bang
3   kiran  chennai

In [92]:
df1.drop('City', axis=1, inplace=True)
df1

     Name  Age   Salary
0  gowrav   24  50000.0
1  gowrav   24  50000.0
2     sai   23      NaN
3   kiran   22  55000.0

In [93]:
df2 = df1.fillna(df1['Salary'].mean())
df2

     Name  Age        Salary
0  gowrav   24  50000.000000
1  gowrav   24  50000.000000
2     sai   23  51666.666667
3   kiran   22  55000.000000

In [94]:
df3 = df2.drop_duplicates()
df3

     Name  Age        Salary
0  gowrav   24  50000.000000
2     sai   23  51666.666667
3   kiran   22  55000.000000